### ISSUE TITLE
Develop signup improvments

### ISSUE THREAD

**Issue by TheDeas343** [Fundo-Patronos/centro-de-carreiras#62]
### Subtasks:

- [x] Create signup error messages
- [x] Create pop-up after signup button
- [x] Improve verify page
- [x] Delete user when send email logic fails (backend)

**Comment by TheDeas343** [comment]
Create signup error messages
Create pop-up after signup button
